// Loads the sprite-sheet animations. Nothing blocks on this: a clip that
// hasn't loaded (or doesn't exist for a character) simply isn't in
// SpriteAnims, and callers fall back to sprites.js vector drawing.

// Multi-frame sprite-sheet animations, generated via AutoSprite (see
// web/assets/release/<character>_sprites/<name>/{spritesheet.png,atlas.json}).
// Each atlas.json describes a uniform grid of frames with pixel coordinates
// and an overall clip duration.
//
// Every character's sprite folders use the same canonical action names
// (below) — no per-character key remapping. A character simply omits the
// folders it doesn't have (e.g. carla has no combat clips at all, boss1 has
// no jump); loadSpriteSheet() already skips setting SpriteAnims[char][action]
// when a sheet 404s, so a missing folder just means that action isn't
// available for that character, with no separate gating table required.
const CANONICAL_ACTIONS = [
  'idle_right', 'walk_right', 'run_right', 'jump_right',
  'punch', 'kick', 'heavy', 'roll',
  'hurt', 'hit_react', 'fall', 'victory', 'dance', 'wave',
];

// giovanni's sprites have moved to web/assets/private/ and are no longer
// shipped, so the character is not loaded here any more.
//
// 'supergere' is not selectable: it's the FURY transformation skin that
// Player swaps to at full meter (see PLAYER_FURY_CHARACTER), but it loads
// through exactly the same path as any other character.
const PlayableCharacters = ['gere', 'giox', 'minion', 'boss1', 'carla', 'supergere'];

// Per-character folder-name overrides. The convention is that a clip's
// folder is named for its canonical action, but supergere's pack was
// exported with capitalised names ('Punch', not 'punch') and uses
// 'Hit React' with a space. Rather than rename the shipped art, map the
// exceptions here; anything absent falls through to the canonical name.
//
// supergere's pack has no 'heavy' or 'wave' clip. 'wave' is cosmetic and is
// simply left absent (it 404s and hasAction() reports it unavailable, the
// same as any other partial character). 'heavy' is a combat move the player
// would otherwise *lose* on transforming, which would make FURY a downgrade
// mid-fight, so it is pointed at the pack's dedicated 'attack_right' clip.
// gere's pack was re-exported from the same tool as supergere's, so it now
// uses byte-identical folder names -- capitalised clips, 'Hit React' with a
// space, and 'attack_right' in place of 'heavy'. The two therefore share one
// alias table rather than keeping a duplicate copy per character.
const AUTOSPRITE_CAPITALISED_CLIPS = {
  punch: 'Punch',
  kick: 'Kick',
  roll: 'Roll',
  hurt: 'Hurt',
  hit_react: 'Hit React',
  fall: 'Fall',
  victory: 'Victory',
  dance: 'Dance',
  heavy: 'attack_right',
};

const SPRITE_FOLDER_ALIASES = {
  supergere: AUTOSPRITE_CAPITALISED_CLIPS,
  gere: AUTOSPRITE_CAPITALISED_CLIPS,
  // The minion's newer clips came from the same exporter, so its reaction
  // and death folders are capitalised too; its older combat clips are not.
  minion: { hurt: 'Hurt', hit_react: 'Hit React' },
};

const CharacterSpriteSheets = {};
for (const character of PlayableCharacters) {
  const sheets = {};
  const aliases = SPRITE_FOLDER_ALIASES[character] || {};
  for (const action of CANONICAL_ACTIONS) {
    sheets[action] = `${character}_sprites/${aliases[action] || action}`;
  }
  CharacterSpriteSheets[character] = sheets;
}

// Prop sprite packs. These are not characters: they have no canonical
// action set, they're never selectable, and each declares only the clips it
// actually has. Kept out of PlayableCharacters so the roster stays the list
// of things you can play as, but they load through the same path and land
// in the same SpriteAnims table.
const PropSpriteSheets = {
  boxingsack: { swing: 'boxingsack_sprites/swing' },
  car: { damage: 'car_sprites/damage', fx: 'car_sprites/fx' },
};

const SpriteAnims = {}; // SpriteAnims[character][action] -> anim data

function loadImage(src) {
  return new Promise((resolve) => {
    const img = new Image();
    img.onload = () => resolve(img);
    img.onerror = () => resolve(null);
    img.src = src;
  });
}

function loadJSON(src) {
  return fetch(src)
    .then((res) => (res.ok ? res.json() : null))
    .catch(() => null);
}

function loadSpriteSheet(character, action, dir) {
  const encodedDir = dir.split('/').map(encodeURIComponent).join('/');
  return Promise.all([
    loadImage(`assets/release/${encodedDir}/spritesheet.png`),
    loadJSON(`assets/release/${encodedDir}/atlas.json`),
    // trim.json is generated by scripts/build-sprite-trim.py and supplies
    // the per-frame bounding box + per-clip scale that atlas.json lacks.
    // Optional: a clip without it just renders as an untrimmed tile.
    loadJSON(`assets/release/${encodedDir}/trim.json`),
  ]).then(([image, atlas, trim]) => {
    if (!image || !atlas) return;
    const frameKeys = Object.keys(atlas.frames).sort((a, b) => Number(a) - Number(b));
    if (!SpriteAnims[character]) SpriteAnims[character] = {};
    // AutoSprite emits two atlas shapes. The character packs use a flat
    // frame ({x,y,w,h}) plus meta.frame_size/duration_s; newer exports use
    // the TexturePacker-style nested {frame:{x,y,w,h}} and omit both meta
    // fields. Normalise here so everything downstream sees one shape,
    // rather than teaching every consumer about the difference.
    const frames = frameKeys.map((k) => {
      const f = atlas.frames[k];
      return f.frame ? f.frame : f;
    });
    const frameSize = atlas.meta.frame_size
      || (frames.length ? { w: frames[0].w, h: frames[0].h } : null);
    SpriteAnims[character][action] = {
      image,
      frames,
      frameSize,
      durationS: atlas.meta.duration_s || 1,
      trim: trim || null,
    };
  });
}

function loadAssets() {
  const sheetPromises = [];
  const packs = { ...CharacterSpriteSheets, ...PropSpriteSheets };
  for (const [character, actions] of Object.entries(packs)) {
    for (const [action, dir] of Object.entries(actions)) {
      sheetPromises.push(loadSpriteSheet(character, action, dir));
    }
  }
  return Promise.all(sheetPromises);
}

// Returns the frame closest to `t` (0..1 normalized progress through the
// clip), or null if the character/action sheet isn't loaded (caller should
// fall back to procedural drawing).
//
// Without trim data the result is the raw grid tile: { image, sx, sy, sw,
// sh, offsetX: 0, lift: 0 }. With it (see scripts/build-sprite-trim.py):
//
//   * sx/sy/sw/sh are tightened to the character's actual pixels, so the
//     box's bottom edge is the character's feet — callers anchor there,
//     which stops clips from hovering at different heights in their tiles.
//   * `lift` is how far this frame's feet sit above the clip's own ground
//     line. Airborne frames encode real vertical motion this way (gere's
//     jump rises 72px), so it must be preserved — anchoring every frame
//     flat to the ground would pin a jumping character to the floor.
//   * `offsetX` re-centres the trimmed box against the tile's centre so a
//     pose that leans left/right doesn't teleport the character sideways.
//
// Sprites are drawn at their authored size: trim.json's `scale` (which
// would normalise every clip to a common character height) is deliberately
// NOT applied — the size differences between clips are a source-art issue
// to be fixed in the sprite sheets themselves, not compensated for here.
function getSpriteFrame(character, action, t) {
  const anim = SpriteAnims[character] && SpriteAnims[character][action];
  // `frames` is guarded rather than assumed: a sheet whose atlas.json is
  // malformed still lands in SpriteAnims, and hasAction() only checks that
  // the entry exists — so a bad atlas would otherwise crash the draw loop
  // every frame instead of falling back to procedural drawing.
  if (!anim || !anim.frames || anim.frames.length === 0) return null;
  const idx = Math.min(anim.frames.length - 1, Math.floor(clamp(t, 0, 0.999) * anim.frames.length));
  const f = anim.frames[idx];

  const trim = anim.trim && anim.trim.frames && anim.trim.frames[String(idx)];
  if (!trim) {
    return { image: anim.image, sx: f.x, sy: f.y, sw: f.w, sh: f.h, offsetX: 0, lift: 0 };
  }
  return {
    image: anim.image,
    sx: f.x + trim.x,
    sy: f.y + trim.y,
    sw: trim.w,
    sh: trim.h,
    offsetX: (trim.x + trim.w / 2) - f.w / 2,
    lift: trim.lift || 0,
  };
}
