// Loads real cropped artwork from the Super Gere texture pack (see textures.jpeg).
// Falls back gracefully: game logic never blocks on load, sprites.js vector
// drawing is used automatically for anything not yet loaded.

// The portrait/face/background art these used to list has moved to
// web/assets/private/ and isn't shipped. Nothing drew any of it — the
// entries were loaded into Assets and then never read — so they are gone
// rather than repointed; add entries back here when something needs them.
const AssetPaths = {};

// Multi-frame sprite-sheet animations, generated via AutoSprite (see
// web/assets/release/<character>_sprites/<name>/{spritesheet.png,atlas.json}).
// Each atlas.json describes a uniform grid of frames with pixel coordinates
// and an overall clip duration.
//
// Every character's sprite folders use the same canonical action names
// (below) — no per-character key remapping. A character simply omits the
// folders it doesn't have (e.g. carla has no combat clips at all, boss1 has
// no jump); loadSpriteSheet() already skips setting SpriteAnims[char][action]
// when a sheet 404s, so a missing folder just means that action isn't
// available for that character, with no separate gating table required.
const CANONICAL_ACTIONS = [
  'idle_right', 'walk_right', 'run_right', 'jump_right',
  'punch', 'kick', 'heavy', 'roll',
  'hurt', 'hit_react', 'fall', 'victory', 'dance', 'wave',
];

// giovanni's sprites have moved to web/assets/private/ and are no longer
// shipped, so the character is not loaded here any more.
const PlayableCharacters = ['gere', 'giox', 'minion', 'boss1', 'carla'];

const CharacterSpriteSheets = {};
for (const character of PlayableCharacters) {
  const sheets = {};
  for (const action of CANONICAL_ACTIONS) {
    sheets[action] = `${character}_sprites/${action}`;
  }
  CharacterSpriteSheets[character] = sheets;
}

const Assets = {};
const SpriteAnims = {}; // SpriteAnims[character][action] -> anim data
let assetsLoaded = false;

function loadImage(src) {
  return new Promise((resolve) => {
    const img = new Image();
    img.onload = () => resolve(img);
    img.onerror = () => resolve(null);
    img.src = src;
  });
}

function loadJSON(src) {
  return fetch(src)
    .then((res) => (res.ok ? res.json() : null))
    .catch(() => null);
}

function loadSpriteSheet(character, action, dir) {
  const encodedDir = dir.split('/').map(encodeURIComponent).join('/');
  return Promise.all([
    loadImage(`assets/release/${encodedDir}/spritesheet.png`),
    loadJSON(`assets/release/${encodedDir}/atlas.json`),
    // trim.json is generated by scripts/build-sprite-trim.py and supplies
    // the per-frame bounding box + per-clip scale that atlas.json lacks.
    // Optional: a clip without it just renders as an untrimmed tile.
    loadJSON(`assets/release/${encodedDir}/trim.json`),
  ]).then(([image, atlas, trim]) => {
    if (!image || !atlas) return;
    const frameKeys = Object.keys(atlas.frames).sort((a, b) => Number(a) - Number(b));
    if (!SpriteAnims[character]) SpriteAnims[character] = {};
    SpriteAnims[character][action] = {
      image,
      frames: frameKeys.map((k) => atlas.frames[k]),
      frameSize: atlas.meta.frame_size,
      durationS: atlas.meta.duration_s || 1,
      trim: trim || null,
    };
  });
}

function loadAssets() {
  const keys = Object.keys(AssetPaths);
  const imagePromises = keys.map((key) =>
    loadImage(AssetPaths[key]).then((img) => {
      if (img) Assets[key] = img;
    })
  );
  const sheetPromises = [];
  for (const [character, actions] of Object.entries(CharacterSpriteSheets)) {
    for (const [action, dir] of Object.entries(actions)) {
      sheetPromises.push(loadSpriteSheet(character, action, dir));
    }
  }
  return Promise.all([...imagePromises, ...sheetPromises]).then(() => {
    assetsLoaded = true;
  });
}

// Returns the frame closest to `t` (0..1 normalized progress through the
// clip), or null if the character/action sheet isn't loaded (caller should
// fall back to procedural drawing).
//
// Without trim data the result is the raw grid tile: { image, sx, sy, sw,
// sh, offsetX: 0, lift: 0 }. With it (see scripts/build-sprite-trim.py):
//
//   * sx/sy/sw/sh are tightened to the character's actual pixels, so the
//     box's bottom edge is the character's feet — callers anchor there,
//     which stops clips from hovering at different heights in their tiles.
//   * `lift` is how far this frame's feet sit above the clip's own ground
//     line. Airborne frames encode real vertical motion this way (gere's
//     jump rises 72px), so it must be preserved — anchoring every frame
//     flat to the ground would pin a jumping character to the floor.
//   * `offsetX` re-centres the trimmed box against the tile's centre so a
//     pose that leans left/right doesn't teleport the character sideways.
//
// Sprites are drawn at their authored size: trim.json's `scale` (which
// would normalise every clip to a common character height) is deliberately
// NOT applied — the size differences between clips are a source-art issue
// to be fixed in the sprite sheets themselves, not compensated for here.
function getSpriteFrame(character, action, t) {
  const anim = SpriteAnims[character] && SpriteAnims[character][action];
  if (!anim || anim.frames.length === 0) return null;
  const idx = Math.min(anim.frames.length - 1, Math.floor(clamp(t, 0, 0.999) * anim.frames.length));
  const f = anim.frames[idx];

  const trim = anim.trim && anim.trim.frames && anim.trim.frames[String(idx)];
  if (!trim) {
    return { image: anim.image, sx: f.x, sy: f.y, sw: f.w, sh: f.h, offsetX: 0, lift: 0 };
  }
  return {
    image: anim.image,
    sx: f.x + trim.x,
    sy: f.y + trim.y,
    sw: trim.w,
    sh: trim.h,
    offsetX: (trim.x + trim.w / 2) - f.w / 2,
    lift: trim.lift || 0,
  };
}
